start =  TEI
TEI = element TEI {teiheader, panel+}
teiheader = element teiheader {filedesc}
filedesc = element filedesc {titleStmt, publicationStmt}
titleStmt = element titleStmt {title}
title = element title {text}
publicationStmt = element publicationStmt {p}
p = element p {text}
panel = element panel {characters, n, balloon*, floatingtext}
characters = attribute characters {list{("RED_Scout" | "RED_Sniper" | "BLU_Spy")*}}
n = attribute n {xsd:integer}
balloon = element balloon {mixed{type, who, emph}}
type = attribute type {"speech" | "diagetic"}
who = attribute who {"RED_Scout"? | "RED_Sniper"? | "BLU_Spy"?}
floatingtext = element floatingtext {subtype, type, text}
subtype = attribute subtype {"symbol"}
emph = element emph {rendition, text}
rendition = attribute rendition {"b" | "i"}